In [1]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('../data/raw/Food_Production.csv')

In [2]:
df.head()

,Food product,Land use change,Animal Feed,Farm,Processing,Transport,Packging,Retail,Total_emissions,Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal),...,Freshwater withdrawals per 100g protein (liters per 100g protein),Freshwater withdrawals per kilogram (liters per kilogram),Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal),Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein),Land use per 1000kcal (m² per 1000kcal),Land use per kilogram (m² per kilogram),Land use per 100g protein (m² per 100g protein),Scarcity-weighted water use per kilogram (liters per kilogram),Scarcity-weighted water use per 100g protein (liters per 100g protein),Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)
0,Wheat & Rye (Bread),0.1,0.0,0.8,0.2,0.1,0.1,0.1,1.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Maize (Meal),0.3,0.0,0.5,0.1,0.1,0.1,0.0,1.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Barley (Beer),0.0,0.0,0.2,0.1,0.0,0.5,0.3,1.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Oatmeal,0.0,0.0,1.4,0.0,0.1,0.1,0.0,1.6,4.281357,...,371.076923,482.4,0.945482,1.907692,2.897446,7.6,5.846154,18786.2,14450.92308,7162.104461
4,Rice,0.0,0.0,3.6,0.1,0.1,0.1,0.1,4.0,9.514379,...,3166.760563,2248.4,1.207271,6.267606,0.759631,2.8,3.943662,49576.3,69825.77465,13449.891480

In [3]:
df.describe

<bound method NDFrame.describe of            Food product  Land use change  Animal Feed  Farm  Processing  \
0   Wheat & Rye (Bread)              0.1          0.0   0.8         0.2
1          Maize (Meal)              0.3          0.0   0.5         0.1
2         Barley (Beer)              0.0          0.0   0.2         0.1
3               Oatmeal              0.0          0.0   1.4         0.0
4                  Rice              0.0          0.0   3.6         0.1
5              Potatoes              0.0          0.0   0.2         0.0
6               Cassava              0.6          0.0   0.2         0.0
7            Cane Sugar              1.2          0.0   0.5         0.0
8            Beet Sugar              0.0          0.0   0.5         0.2
9          Other Pulses              0.0          0.0   1.1         0.0
10                 Peas              0.0          0.0   0.7         0.0
11                 Nuts             -2.1          0.0   2.1         0.0
12           Groundnuts              0.4          0.0   1.4         0.4
13              Soymilk              0.2          0.0   0.1         0.2
14                 Tofu              1.0          0.0   0.5         0.8
15          Soybean Oil              3.1          0.0   1.5         0.3
16             Palm Oil              3.1          0.0   2.1         1.3
17        Sunflower Oil              0.1          0.0   2.1         0.2
18         Rapeseed Oil              0.2          0.0   2.3         0.2
19            Olive Oil             -0.4          0.0   4.3         0.7
20             Tomatoes              0.4          0.0   0.7         0.0
21       Onions & Leeks              0.0          0.0   0.2         0.0
22      Root Vegetables              0.0          0.0   0.2         0.0
23            Brassicas              0.0          0.0   0.3         0.0
24     Other Vegetables              0.0          0.0   0.2         0.1
25         Citrus Fruit             -0.1          0.0   0.3         0.0
26              Bananas              0.0          0.0   0.3         0.1
27               Apples              0.0          0.0   0.2         0.0
28     Berries & Grapes              0.0          0.0   0.7         0.0
29                 Wine             -0.1          0.0   0.6         0.1
30          Other Fruit              0.1          0.0   0.4         0.0
31               Coffee              3.7          0.0  10.4         0.6
32       Dark Chocolate             14.3          0.0   3.7         0.2
33     Beef (beef herd)             16.3          1.9  39.4         1.3
34    Beef (dairy herd)              0.9          2.5  15.7         1.1
35        Lamb & Mutton              0.5          2.4  19.5         1.1
36             Pig Meat              1.5          2.9   1.7         0.3
37         Poultry Meat              2.5          1.8   0.7         0.4
38                 Milk              0.5          0.2   1.5         0.1
39               Cheese              4.5          2.3  13.1         0.7
40                 Eggs              0.7          2.2   1.3         0.0
41        Fish (farmed)              0.5          0.8   3.6         0.0
42     Shrimps (farmed)              0.2          2.5   8.4         0.0

    Transport  Packging  Retail  Total_emissions  \
0         0.1       0.1     0.1              1.4
1         0.1       0.1     0.0              1.1
2         0.0       0.5     0.3              1.1
3         0.1       0.1     0.0              1.6
4         0.1       0.1     0.1              4.0
5         0.1       0.0     0.0              0.3
6         0.1       0.0     0.0              0.9
7         0.8       0.1     0.0              2.6
8         0.6       0.1     0.0              1.4
9         0.1       0.4     0.0              1.6
10        0.1       0.0     0.0              0.8
11        0.1       0.1     0.0              0.2
12        0.1       0.1     0.0              2.4
13        0.1       0.1     0.3              1.0
14        0.2       0.2     0.3              3.0
15        0.3       0.8     0.0              6.0
16        0.2       0.9     0.0              7.6
17        0.2       0.9     0.0              3.5
18        0.2       0.8     0.0              3.7
19        0.5       0.9     0.0              6.0
20        0.2       0.1     0.0              1.4
21        0.1       0.0     0.0              0.3
22        0.1       0.0     0.0              0.3
23        0.1       0.0     0.0              0.4
24        0.2       0.0     0.0              0.5
25        0.1       0.0     0.0              0.3
26        0.3       0.1     0.0              0.8
27        0.1       0.0     0.0              0.3
28        0.2       0.2     0.0              1.1
29        0.1       0.7     0.0              1.4
30        0.2       0.0     0.0              0.7
31        0.1       1.6     0.1             16.5
32        0.1       0.4     0.0             18.7
33        0.3       0.2     0.2             59.6
34        0.4       0.3     0.2             21.1
35        0.5       0.3     0.2             24.5
36        0.3       0.3     0.2              7.2
37        0.3       0.2     0.2              6.1
38        0.1       0.1     0.3              2.8
39        0.1       0.2     0.3             21.2
40        0.1       0.2     0.0              4.5
41        0.1       0.1     0.0              5.1
42        0.2       0.3     0.2             11.8

    Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)  ...  \
0                                                 NaN         ...
1                                                 NaN         ...
2                                                 NaN         ...
3                                            4.281357         ...
4                                            9.514379         ...
5                                            4.754098         ...
6                                            0.708419         ...
7                                            4.820513         ...
8                                            1.541311         ...
9                                            5.008798         ...
10                                           2.173410         ...
11                                           3.113821         ...
12                                           2.437931         ...
13                                                NaN         ...
14                                                NaN         ...
15                                                NaN         ...
16                                           1.207014         ...
17                                           5.730769         ...
18                                           2.170814         ...
19                                           4.214932         ...
20                                          39.526316         ...
21                                           8.756757         ...
22                                           4.351351         ...
23                                          29.470588         ...
24                                                NaN         ...
25                                           7.000000         ...
26                                           5.483333         ...
27                                           3.020833         ...
28                                          10.736842         ...
29                                                NaN         ...
30                                                NaN         ...
31                                         197.357143         ...
32                                          16.843327         ...
33                                         110.406593         ...
34                                         133.805861         ...
35                                          30.640379         ...
36                                          31.958159         ...
37                                          26.324324         ...
38                                          17.750000         ...
39                                          25.418605         ...
40                                          15.111111         ...
41                                         131.351955         ...
42                                                NaN         ...

    Freshwater withdrawals per 100g protein (liters per 100g protein)  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                          371.076923
4                                         3166.760563
5                                          347.647059
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                          203.503036
10                                         178.487849
11                                        2531.414574
12                                         707.524828
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                        3361.818182
21                                         110.000000
22                                         284.000000
23                                        1085.454545
24                                                NaN
25                                        1378.333333
26                                        1272.222222
27                                        6003.333333
28                                        4196.000000
29                                                NaN
30                                                NaN
31                                          32.375000
32                                        1081.200000
33                                         727.783350
34                                        1375.025329
35                                         900.949525
36                                        1109.888752
37                                         381.062356
38                                        1903.636364
39                                        2538.586957
40                                         520.638068
41                                        1618.636264
42                                                NaN

    Freshwater withdrawals per kilogram (liters per kilogram)  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                               482.4
4                                              2248.4
5                                                59.1
6                                                 0.0
7                                               620.1
8                                               217.7
9                                               435.7
10                                              396.6
11                                             4133.8
12                                             1852.3
13                                               27.8
14                                                NaN
15                                              414.6
16                                                6.4
17                                             1007.9
18                                              237.7
19                                             2141.8
20                                              369.8
21                                               14.3
22                                               28.4
23                                              119.4
24                                              102.5
25                                               82.7
26                                              114.5
27                                              180.1
28                                              419.6
29                                               78.9
30                                              153.5
31                                               25.9
32                                              540.6
33                                             1451.2
34                                             2714.3
35                                             1802.8
36                                             1795.8
37                                              660.0
38                                              628.2
39                                             5605.2
40                                              577.7
41                                             3691.3
42                                                NaN

    Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                            0.945482
4                                            1.207271
5                                            0.628415
6                                            1.355236
7                                            0.911681
8                                            0.515670
9                                            0.524927
10                                           0.283237
11                                           0.069919
12                                           0.556897
13                                                NaN
14                                                NaN
15                                                NaN
16                                           0.828054
17                                           0.407240
18                                           0.426471
19                                           0.613122
20                                          11.000000
21                                           1.351351
22                                           1.162162
23                                           3.000000
24                                                NaN
25                                           1.218750
26                                           1.433333
27                                           0.895833
28                                           2.684211
29                                                NaN
30                                                NaN
31                                          50.946429
32                                           9.023211
33                                          36.439560
34                                          12.197802
35                                          12.529968
36                                           5.150628
37                                           5.335135
38                                           5.250000
39                                           6.170543
40                                           3.243056
41                                           7.614525
42                                                NaN

    Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                            1.907692
4                                            6.267606
5                                            2.705882
6                                           14.666667
7                                                 NaN
8                                                 NaN
9                                            0.836058
10                                           0.441044
11                                           0.263319
12                                           1.233766
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                          19.000000
21                                           3.846154
22                                           4.300000
23                                           4.636364
24                                                NaN
25                                           6.500000
26                                           9.555556
27                                          14.333333
28                                          15.300000
29                                                NaN
30                                                NaN
31                                          35.662500
32                                          93.300000
33                                          49.889669
34                                          16.869301
35                                          19.850075
36                                           7.608158
37                                           5.698614
38                                           9.500000
39                                          10.815217
40                                           4.208724
41                                           5.976759
42                                                NaN

    Land use per 1000kcal (m² per 1000kcal)  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                  2.897446
4                                  0.759631
5                                  1.202186
6                                  1.858316
7                                  0.581197
8                                  0.521368
9                                  4.565982
10                                 2.156069
11                                 2.107317
12                                 1.570690
13                                      NaN
14                                      NaN
15                                      NaN
16                                 0.273756
17                                 1.997738
18                                 1.202489
19                                 2.976244
20                                 4.210526
21                                 1.054054
22                                 0.891892
23                                 3.235294
24                                      NaN
25                                 2.687500
26                                 3.216667
27                                 1.312500
28                                 4.228070
29                                      NaN
30                                      NaN
31                                38.607143
32                                13.338491
33                               119.490842
34                                15.838828
35                               116.659306
36                                 7.263598
37                                 6.605405
38                                14.916667
39                                22.684755
40                                 4.354167
41                                 4.698324
42                                      NaN

    Land use per kilogram (m² per kilogram)  \
0                                       NaN
1                                       NaN
2                                       NaN

In [4]:
df.columns

Index(['Food product', 'Land use change', 'Animal Feed', 'Farm', 'Processing',
       'Transport', 'Packging', 'Retail', 'Total_emissions',
       'Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)',
       'Eutrophying emissions per kilogram (gPO₄eq per kilogram)',
       'Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein)',
       'Freshwater withdrawals per 1000kcal (liters per 1000kcal)',
       'Freshwater withdrawals per 100g protein (liters per 100g protein)',
       'Freshwater withdrawals per kilogram (liters per kilogram)',
       'Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)',
       'Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)',
       'Land use per 1000kcal (m² per 1000kcal)',
       'Land use per kilogram (m² per kilogram)',
       'Land use per 100g protein (m² per 100g protein)',
       'Scarcity-weighted water use per kilogram (liters per kilogram)',
       'Scarcity-weighted water use per 100g protein (liters per 100g protein)',
       'Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)'],
      dtype='object')

In [5]:
# Cleaning data: Checking for Missing Values

df.isnull().sum()

Food product                                                                0
Land use change                                                             0
Animal Feed                                                                 0
Farm                                                                        0
Processing                                                                  0
Transport                                                                   0
Packging                                                                    0
Retail                                                                      0
Total_emissions                                                             0
Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)                   10
Eutrophying emissions per kilogram (gPO₄eq per kilogram)                    5
Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein)      16
Freshwater withdrawals per 1000kcal (liters per 1000kcal)                  13
Freshwater withdrawals per 100g protein (liters per 100g protein)          17
Freshwater withdrawals per kilogram (liters per kilogram)                   5
Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)               10
Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)       16
Land use per 1000kcal (m² per 1000kcal)                                    10
Land use per kilogram (m² per kilogram)                                     5
Land use per 100g protein (m² per 100g protein)                            16
Scarcity-weighted water use per kilogram (liters per kilogram)              5
Scarcity-weighted water use per 100g protein (liters per 100g protein)     17
Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)    13
dtype: int64

In [6]:
df.dtypes

Food product                                                                object
Land use change                                                            float64
Animal Feed                                                                float64
Farm                                                                       float64
Processing                                                                 float64
Transport                                                                  float64
Packging                                                                   float64
Retail                                                                     float64
Total_emissions                                                            float64
Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)                   float64
Eutrophying emissions per kilogram (gPO₄eq per kilogram)                   float64
Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein)      float64
Freshwater withdrawals per 1000kcal (liters per 1000kcal)                  float64
Freshwater withdrawals per 100g protein (liters per 100g protein)          float64
Freshwater withdrawals per kilogram (liters per kilogram)                  float64
Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)               float64
Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)       float64
Land use per 1000kcal (m² per 1000kcal)                                    float64
Land use per kilogram (m² per kilogram)                                    float64
Land use per 100g protein (m² per 100g protein)                            float64
Scarcity-weighted water use per kilogram (liters per kilogram)             float64
Scarcity-weighted water use per 100g protein (liters per 100g protein)     float64
Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)    float64
dtype: object

In [7]:
df.columns

Index(['Food product', 'Land use change', 'Animal Feed', 'Farm', 'Processing',
       'Transport', 'Packging', 'Retail', 'Total_emissions',
       'Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)',
       'Eutrophying emissions per kilogram (gPO₄eq per kilogram)',
       'Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein)',
       'Freshwater withdrawals per 1000kcal (liters per 1000kcal)',
       'Freshwater withdrawals per 100g protein (liters per 100g protein)',
       'Freshwater withdrawals per kilogram (liters per kilogram)',
       'Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)',
       'Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)',
       'Land use per 1000kcal (m² per 1000kcal)',
       'Land use per kilogram (m² per kilogram)',
       'Land use per 100g protein (m² per 100g protein)',
       'Scarcity-weighted water use per kilogram (liters per kilogram)',
       'Scarcity-weighted water use per 100g protein (liters per 100g protein)',
       'Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)'],
      dtype='object')

In [8]:
#checking missing values.

In [9]:
# Columns with missing values, num.columns
columns_to_fill = [
    'Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)',
    'Eutrophying emissions per kilogram (gPO₄eq per kilogram)',
    'Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein)',
    'Freshwater withdrawals per 1000kcal (liters per 1000kcal)',
    'Freshwater withdrawals per 100g protein (liters per 100g protein)',
    'Freshwater withdrawals per kilogram (liters per kilogram)',
    'Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)',
    'Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)',
    'Land use per 1000kcal (m² per 1000kcal)',
    'Land use per kilogram (m² per kilogram)',
    'Land use per 100g protein (m² per 100g protein)',
    'Scarcity-weighted water use per kilogram (liters per kilogram)',
    'Scarcity-weighted water use per 100g protein (liters per 100g protein)',
    'Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)'
]

# Fill missing values in specified columns with 0
df[columns_to_fill] = df[columns_to_fill].fillna(0)

In [10]:
df.isnull().sum()

Food product                                                               0
Land use change                                                            0
Animal Feed                                                                0
Farm                                                                       0
Processing                                                                 0
Transport                                                                  0
Packging                                                                   0
Retail                                                                     0
Total_emissions                                                            0
Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)                   0
Eutrophying emissions per kilogram (gPO₄eq per kilogram)                   0
Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein)      0
Freshwater withdrawals per 1000kcal (liters per 1000kcal)                  0
Freshwater withdrawals per 100g protein (liters per 100g protein)          0
Freshwater withdrawals per kilogram (liters per kilogram)                  0
Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)               0
Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)       0
Land use per 1000kcal (m² per 1000kcal)                                    0
Land use per kilogram (m² per kilogram)                                    0
Land use per 100g protein (m² per 100g protein)                            0
Scarcity-weighted water use per kilogram (liters per kilogram)             0
Scarcity-weighted water use per 100g protein (liters per 100g protein)     0
Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)    0
dtype: int64

In [11]:
df.shape

(43, 23)

In [12]:
# Dictionary mapping current column names to suggested new names
new_column_names = {
    'Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)': 'Eutrophying emissions per 1000kcal',
    'Eutrophying emissions per kilogram (gPO₄eq per kilogram)': 'Eutrophying emissions per kilogram',
    'Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein)': 'Eutrophying emissions per 100g protein',
    'Freshwater withdrawals per 1000kcal (liters per 1000kcal)': 'Freshwater withdrawals per 1000kcal',
    'Freshwater withdrawals per 100g protein (liters per 100g protein)': 'Freshwater withdrawals per 100g protein',
    'Freshwater withdrawals per kilogram (liters per kilogram)': 'Freshwater withdrawals per kilogram',
    'Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)': 'Greenhouse gas emissions per 1000kcal',
    'Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)': 'Greenhouse gas emissions per 100g protein',
    'Land use per 1000kcal (m² per 1000kcal)': 'Land use per 1000kcal',
    'Land use per kilogram (m² per kilogram)': 'Land use per kilogram',
    'Land use per 100g protein (m² per 100g protein)': 'Land use per 100g protein',
    'Scarcity-weighted water use per kilogram (liters per kilogram)': 'Scarcity-weighted water use per kilogram',
    'Scarcity-weighted water use per 100g protein (liters per 100g protein)': 'Scarcity-weighted water use per 100g protein',
    'Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)': 'Scarcity-weighted water use per 1000kcal'
}

df = df.rename(columns=new_column_names)

In [13]:
df.columns

Index(['Food product', 'Land use change', 'Animal Feed', 'Farm', 'Processing',
       'Transport', 'Packging', 'Retail', 'Total_emissions',
       'Eutrophying emissions per 1000kcal',
       'Eutrophying emissions per kilogram',
       'Eutrophying emissions per 100g protein',
       'Freshwater withdrawals per 1000kcal',
       'Freshwater withdrawals per 100g protein',
       'Freshwater withdrawals per kilogram',
       'Greenhouse gas emissions per 1000kcal',
       'Greenhouse gas emissions per 100g protein', 'Land use per 1000kcal',
       'Land use per kilogram', 'Land use per 100g protein',
       'Scarcity-weighted water use per kilogram',
       'Scarcity-weighted water use per 100g protein',
       'Scarcity-weighted water use per 1000kcal'],
      dtype='object')

In [14]:
print(df.duplicated().sum()/df.shape[0])

0.0

In [15]:
# columns to drop, no needed
columns_to_drop = [
    'Eutrophying emissions per 1000kcal',
    'Eutrophying emissions per 100g protein',
    'Freshwater withdrawals per 1000kcal',
    'Freshwater withdrawals per 100g protein',
    'Greenhouse gas emissions per 1000kcal',
    'Land use per 1000kcal',
    'Land use per 100g protein',
    'Scarcity-weighted water use per 100g protein',
    'Scarcity-weighted water use per 1000kcal'
]

# Drop the specified columns
df = df.drop(columns=columns_to_drop, axis=1)

In [16]:
df.columns

Index(['Food product', 'Land use change', 'Animal Feed', 'Farm', 'Processing',
       'Transport', 'Packging', 'Retail', 'Total_emissions',
       'Eutrophying emissions per kilogram',
       'Freshwater withdrawals per kilogram',
       'Greenhouse gas emissions per 100g protein', 'Land use per kilogram',
       'Scarcity-weighted water use per kilogram'],
      dtype='object')

In [17]:
def round_numeric_columns(df: pd.DataFrame) -> pd.DataFrame:
    df2=df.copy()
    numeric_columns = df.select_dtypes(include='number')
    df2[numeric_columns.columns] = df2[numeric_columns.columns].round(2)
    return df2

In [18]:
display(round_numeric_columns(df))

,Food product,Land use change,Animal Feed,Farm,Processing,Transport,Packging,Retail,Total_emissions,Eutrophying emissions per kilogram,Freshwater withdrawals per kilogram,Greenhouse gas emissions per 100g protein,Land use per kilogram,Scarcity-weighted water use per kilogram
0,Wheat & Rye (Bread),0.1,0.0,0.8,0.2,0.1,0.1,0.1,1.4,0.00,0.0,0.00,0.00,0.0
1,Maize (Meal),0.3,0.0,0.5,0.1,0.1,0.1,0.0,1.1,0.00,0.0,0.00,0.00,0.0
2,Barley (Beer),0.0,0.0,0.2,0.1,0.0,0.5,0.3,1.1,0.00,0.0,0.00,0.00,0.0
3,Oatmeal,0.0,0.0,1.4,0.0,0.1,0.1,0.0,1.6,11.23,482.4,1.91,7.60,18786.2
4,Rice,0.0,0.0,3.6,0.1,0.1,0.1,0.1,4.0,35.07,2248.4,6.27,2.80,49576.3
5,Potatoes,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,3.48,59.1,2.71,0.88,2754.2
6,Cassava,0.6,0.0,0.2,0.0,0.1,0.0,0.0,0.9,0.69,0.0,14.67,1.81,0.0
7,Cane Sugar,1.2,0.0,0.5,0.0,0.8,0.1,0.0,2.6,16.92,620.1,0.00,2.04,16438.6
8,Beet Sugar,0.0,0.0,0.5,0.2,0.6,0.1,0.0,1.4,5.41,217.7,0.00,1.83,9493.3
9,Other Pulses,0.0,0.0,1.1,0.0,0.1,0.4,0.0,1.6,17.08,435.7,0.84,15.57,22477.4
10,Peas,0.0,0.0,0.7,0.0,0.1,0.0,0.0,0.8,7.52,396.6,0.44,7.46,27948.2
11,Nuts,-2.1,0.0,2.1,0.0,0.1,0.1,0.0,0.2,19.15,4133.8,0.26,12.96,229889.8
12,Groundnuts,0.4,0.0,1.4,0.4,0.1,0.1,0.0,2.4,14.14,1852.3,1.23,9.11,61797.9
13,Soymilk,0.2,0.0,0.1,0.2,0.1,0.1,0.3,1.0,1.06,27.8,0.00,0.66,955.6
14,Tofu,1.0,0.0,0.5,0.8,0.2,0.2,0.3,3.0,0.00,0.0,0.00,0.00,0.0
15,Soybean Oil,3.1,0.0,1.5,0.3,0.3,0.8,0.0,6.0,11.69,414.6,0.00,10.52,14888.2
16,Palm Oil,3.1,0.0,2.1,1.3,0.2,0.9,0.0,7.6,10.67,6.4,0.00,2.42,36.2
17,Sunflower Oil,0.1,0.0,2.1,0.2,0.2,0.9,0.0,3.5,50.66,1007.9,0.00,17.66,36369.4
18,Rapeseed Oil,0.2,0.0,2.3,0.2,0.2,0.8,0.0,3.7,19.19,237.7,0.00,10.63,10593.7
19,Olive Oil,-0.4,0.0,4.3,0.7,0.5,0.9,0.0,6.0,37.26,2141.8,0.00,26.31,177480.2
20,Tomatoes,0.4,0.0,0.7,0.0,0.2,0.1,0.0,1.4,7.51,369.8,19.00,0.80,5335.7
21,Onions & Leeks,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,3.24,14.3,3.85,0.39,932.0
22,Root Vegetables,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,1.61,28.4,4.30,0.33,929.2
23,Brassicas,0.0,0.0,0.3,0.0,0.1,0.0,0.0,0.4,5.01,119.4,4.64,0.55,8455.1
24,Other Vegetables,0.0,0.0,0.2,0.1,0.2,0.0,0.0,0.5,2.27,102.5,0.00,0.38,4911.4
25,Citrus Fruit,-0.1,0.0,0.3,0.0,0.1,0.0,0.0,0.3,2.24,82.7,6.50,0.86,4662.7
26,Bananas,0.0,0.0,0.3,0.1,0.3,0.1,0.0,0.8,3.29,114.5,9.56,1.93,661.9
27,Apples,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,1.45,180.1,14.33,0.63,12948.6
28,Berries & Grapes,0.0,0.0,0.7,0.0,0.2,0.2,0.0,1.1,6.12,419.6,15.30,2.41,21162.1
29,Wine,-0.1,0.0,0.6,0.1,0.1,0.7,0.0,1.4,4.57,78.9,0.00,1.78,1149.3
30,Other Fruit,0.1,0.0,0.4,0.0,0.2,0.0,0.0,0.7,2.43,153.5,0.00,0.89,9533.1
31,Coffee,3.7,0.0,10.4,0.6,0.1,1.6,0.1,16.5,110.52,25.9,35.66,21.62,337.0
32,Dark Chocolate,14.3,0.0,3.7,0.2,0.1,0.4,0.0,18.7,87.08,540.6,93.30,68.96,2879.2
33,Beef (beef herd),16.3,1.9,39.4,1.3,0.3,0.2,0.2,59.6,301.41,1451.2,49.89,326.21,34732.5
34,Beef (dairy herd),0.9,2.5,15.7,1.1,0.4,0.3,0.2,21.1,365.29,2714.3,16.87,43.24,119805.2
35,Lamb & Mutton,0.5,2.4,19.5,1.1,0.5,0.3,0.2,24.5,97.13,1802.8,19.85,369.81,141925.0
36,Pig Meat,1.5,2.9,1.7,0.3,0.3,0.3,0.2,7.2,76.38,1795.8,7.61,17.36,66867.4
37,Poultry Meat,2.5,1.8,0.7,0.4,0.3,0.2,0.2,6.1,48.70,660.0,5.70,12.22,14177.9
38,Milk,0.5,0.2,1.5,0.1,0.1,0.1,0.3,2.8,10.65,628.2,9.50,8.95,19786.3
39,Cheese,4.5,2.3,13.1,0.7,0.1,0.2,0.3,21.2,98.37,5605.2,10.82,87.79,180850.6
40,Eggs,0.7,2.2,1.3,0.0,0.1,0.2,0.0,4.5,21.76,577.7,4.21,6.27,17982.7
41,Fish (farmed),0.5,0.8,3.6,0.0,0.1,0.1,0.0,5.1,235.12,3691.3,5.98,8.41,41572.2
42,Shrimps (farmed),0.2,2.5,8.4,0.0,0.2,0.3,0.2,11.8,0.00,0.0,0.00,0.00,0.0

In [19]:
#Applying function round to 2 decimal numeric columns to the dataframe
#redefining dataframe
df = round_numeric_columns(df)

In [20]:
df.head()

,Food product,Land use change,Animal Feed,Farm,Processing,Transport,Packging,Retail,Total_emissions,Eutrophying emissions per kilogram,Freshwater withdrawals per kilogram,Greenhouse gas emissions per 100g protein,Land use per kilogram,Scarcity-weighted water use per kilogram
0,Wheat & Rye (Bread),0.1,0.0,0.8,0.2,0.1,0.1,0.1,1.4,0.00,0.0,0.00,0.0,0.0
1,Maize (Meal),0.3,0.0,0.5,0.1,0.1,0.1,0.0,1.1,0.00,0.0,0.00,0.0,0.0
2,Barley (Beer),0.0,0.0,0.2,0.1,0.0,0.5,0.3,1.1,0.00,0.0,0.00,0.0,0.0
3,Oatmeal,0.0,0.0,1.4,0.0,0.1,0.1,0.0,1.6,11.23,482.4,1.91,7.6,18786.2
4,Rice,0.0,0.0,3.6,0.1,0.1,0.1,0.1,4.0,35.07,2248.4,6.27,2.8,49576.3

In [21]:
#save datafile cleaned
df.to_csv('../data/cleaned/Food_Production_cleaned.csv', index=False)

In [22]:
#Storing the function round numeric columns

In [23]:
%%writefile my_function.py
def round_numeric_columns(df: pd.DataFrame) -> pd.DataFrame:
    df2=df.copy()
    numeric_columns = df.select_dtypes(include='number')
    df2[numeric_columns.columns] = df2[numeric_columns.columns].round(2)
    return df2

Writing my_function.py